### PR TITLE
Hide isSymbolicLink from directory

### PR DESCRIPTION
**Pull request by bgamari**
This was exposed in directory-1.2.6.0

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks! Instead of hiding the import, would you be willing to rewrite this so that the `cabal` file bounds `directory < 1.2.6.0`?

**Comment by bgamari** [comment]
Jonathan Daugherty <notifications@github.com> writes:

> Thanks! Instead of hiding the import, would you be willing to rewrite this so that the `cabal` file bounds `directory < 1.2.6.0`?
>
I'm not sure that's a good idea; GHC 8.0 will ship with
`directory > 1.2.6` and setting a restrictive upper bound like this
would unnecessarily preclude installation plans for packages that link
to both `vty-ui` and `ghc`.

**Comment by jtdaugherty** [comment]
Since `vty-ui` is deprecated I'm not too inclined to make it work with newer GHC releases, but since the `hiding` clause will not cause any trouble on most other releases then it doesn't strike me as that bad.

**Comment by jtdaugherty** [comment]
I'll also add that `directory` exposing a new function in `1.2.6` is a violation of the PVP and never should have been done. :)

**Pull request merged**
