### PR TITLE
Fix `instance Arbitrary (MaybeDefault a)` for latest vty

### PR DESCRIPTION
**Pull request by ktvoelker**

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for the fix. Presumably this fix is relevant to a specific version of `vty`?

**Comment by jtdaugherty** [comment]
Oh! I just realized it's relevant to the version of `vty` including the addition of the `Read` instance that *I wrote*. :)

**Comment by jtdaugherty** [comment]
For what it's worth, `vty-ui` will soon be deprecated by `brick`; check it out!

https://github.com/jtdaugherty/brick

**Comment by ktvoelker** [comment]
Cool!

**Pull request merged**
